/*
 * File: app/view/DemoWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.DemoWindow', {
    extend: 'Ext.window.Window',

    height: 396,
    id: 'DemoWindow',
    width: 589,
    layout: {
        type: 'border'
    },
    title: 'DemoWindow',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    region: 'center',
                    id: 'demoForm',
                    layout: {
                        type: 'column'
                    },
                    bodyPadding: 10,
                    header: false,
                    title: '表单'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    split: false,
                    dock: 'bottom',
                    id: 'formToolbar',
                    layout: {
                        pack: 'end',
                        padding: 3,
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'button',
                            id: 'btnSave',
                            text: '保存',
                            listeners: {
                                click: {
                                    fn: me.onBtnSaveClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'btnCancel',
                            text: '取消',
                            listeners: {
                                click: {
                                    fn: me.onBtnCancelClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onBtnSaveClick: function(button, e, eOpts) {

    },

    onBtnCancelClick: function(button, e, eOpts) {
        this.store.reload();
    }

});