/*
 * File: classes/view/Common.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Common', {
    extend: 'Ext.Base',
    alias: 'widget.Common',

    statics: {
        onAjaxException: function(response) {
            if(response.status === 200)
            {
                var result = Ext.JSON.decode(response.responseText);
                Ext.Msg.alert('操作异常 '+response.status, result.data);
            }
            else
            {
                Ext.Msg.alert('操作异常 '+response.status, response.responseText);
            }
        },

        ajax: function(config) {
            if(config.component)
            {
                if(config.message)
                {
                    config.component.setLoading(config.message);
                }
                else
                {
                    config.component.setLoading('正在下载...');
                }
            }
            Ext.Ajax.request(
            {
                url : config.url,
                params : config.params,
                method : 'post',

                callback : function(options, success, response)
                {
                    if(config.component)
                    {
                        config.component.setLoading(false);
                    }
                    if (success)
                    {
                        config.callback(Ext.JSON.decode(response.responseText),options, success, response);// 调用回调函数
                    }
                    else
                    {
                        if(config.component)
                        {
                            if(+response.status === 403){
                                config.component.close();
                            }
                        }
                        Gotom.view.Common.onAjaxException(response);
                    }
                }
            });
        },

        createTreeStore: function(URL, pid) {
            var store = Ext.create("Ext.data.TreeStore",
                {
                    defaultRootId : pid,
                    clearOnLoad : true,
                    nodeParam : 'id',
                    fields: [
                    {
                        name: 'id'
                    },
                    {
                        name: 'sort',
                        type: 'int'
                    },
                    {
                        name: 'text'
                    },
                    {
                        name: 'iconCls'
                    },
                    {
                        name: 'leaf',
                        type: 'boolean'
                    },
                    {
                        name: 'type'
                    },
                    {
                        name: 'resource'
                    },
                    {
                        name: 'component'
                    },
                    {
                        name: 'parentId'
                    }
                    ],
                    proxy :
                    {
                        type : 'ajax',
                        url : URL            
                    }
                });
            return store;
        },

        getQueryParam: function(name) {
            var regex = RegExp('[?&]' + name + '=([^&]*)');
            var scriptEls = document.getElementsByTagName('script');
            var path = scriptEls[scriptEls.length - 1].src;
            var match = regex.exec(location.search) || regex.exec(path);
            return match && decodeURIComponent(match[1]);
        },

        addQueryParam: function(url, name, value) {
            var path = url;
            if (value !== null && value.length > 0)
            {
                if (url.indexOf('?') >= 0)
                {
                    path = url + '&' + name + '=' + value;
                }
                else
                {
                    path = url + '?' + name + '=' + value;
                }
            }
            return path;
        },

        onTreeParentNodeChecked: function(node, checked) {
            if(node.parentNode !== null)
            {
                if(node.parentNode.childNodes.length >0)
                {
                    var parentCheck = false;
                    Ext.each(node.parentNode.childNodes,function(childNode)
                    {
                        if(childNode.data.checked)
                        {
                            parentCheck = true;
                        }
                    });
                    node.parentNode.set('checked', parentCheck);
                    Gotom.view.Common.onTreeParentNodeChecked(node.parentNode,checked);
                }
            }
        },

        onTreeChildNodesChecked: function(node, checked) {
            Ext.each(node.childNodes,function(childNode)
            {
                childNode.set('checked', checked);  
                if(childNode.childNodes.length >0)
                {
                    Gotom.view.Common.onTreeChildNodesChecked(childNode,checked);
                }
            });

        },

        onTreePanelCheckChange: function(node, checked) {
            Gotom.view.Common.onTreeChildNodesChecked(node,checked);
            Gotom.view.Common.onTreeParentNodeChecked(node,checked);

        },

        formSubmit: function(config) {
            if (config.form().isValid())
            {
                var msg = '正在保存数据，稍后...';
                if(config.msg){
                    msg = config.msg;
                }
                config.form().submit(
                {
                    url : config.url,
                    method : 'POST',
                    waitMsg : msg,
                    success : config.callback,
                    failure : function(f, action)
                    {
                        Gotom.view.Common.onAjaxException(action.response);          
                    }
                });
            }
        }
    }
});