/*
 * File: classes/view/RightPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Gotom.view.RightPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.RightPanel',

    border: false,
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'treepanel',
                    region: 'center',
                    id: 'RightTreePanel',
                    title: 'My Tree Panel',
                    viewConfig: {
                        id: 'RightTreePanelView'
                    },
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            id: 'RightTreePanelToolbar'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});