/*
 * File: app/view/DemoViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.DemoViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'MyApp.view.DemoTreeGrid'
    ],

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'DemoTreeGrid',
                    region: 'center',
                    store: 'TreeStore'
                }
            ],
            listeners: {
                render: {
                    fn: me.onViewportRender,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onViewportRender: function(component, eOpts) {
        alert(id);
    },

    loadData: function(id) {
        var parentId = '0000';
        var wait = Ext.Msg.wait("正在载入......", "操作提示");
        Ext.Ajax.request(
        {
            url : '../p/organization.do',
            method : 'POST',
            params:{  
                id:id,
                parentId:parentId
            },  
            success : function(response, options)
            {
                var result = Ext.JSON.decode(response.responseText);
                wait.close();
                //alert(result.text);
            },
            failure : function(response, options)
            {
                wait.close();
                Ext.Msg.alert("操作提示", "载入失败");
            }
        });
    }

});