/*
 * File: classes/view/EnergyCollectWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ems.view.EnergyCollectWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.EnergyCollectWindow',

    height: 312,
    id: 'EnergyCollectWindow',
    width: 523,
    resizeHandles: 'n',
    layout: {
        type: 'border'
    },
    title: '数据采集',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    id: 'mytoolbar',
                    layout: {
                        pack: 'end',
                        padding: 3,
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'button',
                            id: 'btnSave',
                            iconCls: 'icon-save',
                            text: '保存',
                            listeners: {
                                click: {
                                    fn: me.onBtnSaveClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'btnReset',
                            iconCls: 'icon-close',
                            text: '关闭',
                            listeners: {
                                click: {
                                    fn: me.onBtnResetClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'form',
                    region: 'center',
                    id: 'ecform',
                    layout: {
                        type: 'column'
                    },
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'building.name',
                            padding: 2,
                            fieldLabel: '建筑名称',
                            labelAlign: 'right',
                            name: 'name',
                            readOnly: true
                        },
                        {
                            xtype: 'hiddenfield',
                            id: 'building.id',
                            width: 150,
                            fieldLabel: 'Label',
                            name: 'buildingId'
                        },
                        {
                            xtype: 'datefield',
                            id: 'collectDate',
                            padding: 2,
                            fieldLabel: '采集时间',
                            labelAlign: 'right',
                            name: 'collectDate',
                            value: '12/01/2013'
                        },
                        {
                            xtype: 'numberfield',
                            id: 'electric',
                            padding: 2,
                            fieldLabel: '电',
                            labelAlign: 'right',
                            name: 'electric'
                        },
                        {
                            xtype: 'numberfield',
                            id: 'water',
                            padding: 2,
                            fieldLabel: '水',
                            labelAlign: 'right',
                            name: 'water'
                        },
                        {
                            xtype: 'numberfield',
                            id: 'gas',
                            padding: 2,
                            fieldLabel: '燃气',
                            labelAlign: 'right',
                            name: 'gas'
                        },
                        {
                            xtype: 'numberfield',
                            id: 'heating',
                            padding: 2,
                            fieldLabel: '集中供热量',
                            labelAlign: 'right',
                            name: 'heating'
                        },
                        {
                            xtype: 'numberfield',
                            id: 'otherEnergy',
                            padding: 2,
                            fieldLabel: '其它能源',
                            labelAlign: 'right',
                            name: 'otherEnergy'
                        },
                        {
                            xtype: 'numberfield',
                            id: 'coal',
                            padding: 2,
                            fieldLabel: '煤',
                            labelAlign: 'right',
                            name: 'coal'
                        },
                        {
                            xtype: 'numberfield',
                            id: 'lpg',
                            padding: 2,
                            fieldLabel: ' 液化石油气',
                            labelAlign: 'right',
                            name: 'lpg'
                        },
                        {
                            xtype: 'numberfield',
                            id: 'manufacturedGas',
                            padding: 2,
                            fieldLabel: '人工煤气',
                            labelAlign: 'right',
                            name: 'manufacturedGas'
                        },
                        {
                            xtype: 'numberfield',
                            id: 'gasoline',
                            padding: 2,
                            fieldLabel: '汽油',
                            labelAlign: 'right',
                            name: 'gasoline'
                        },
                        {
                            xtype: 'numberfield',
                            id: 'kerosene',
                            padding: 2,
                            fieldLabel: '煤油',
                            labelAlign: 'right',
                            name: 'kerosene'
                        },
                        {
                            xtype: 'numberfield',
                            id: 'solarThermal',
                            padding: 2,
                            fieldLabel: '太阳能光热利用系统集热器面积',
                            labelAlign: 'right',
                            name: 'solarThermal'
                        },
                        {
                            xtype: 'numberfield',
                            id: 'geothermal',
                            padding: 2,
                            fieldLabel: '浅层地热能利用系统装机容量',
                            labelAlign: 'right',
                            name: 'geothermal'
                        },
                        {
                            xtype: 'numberfield',
                            id: 'geothermalAuxiliary',
                            padding: 2,
                            fieldLabel: '浅层地热能利用系统辅助热源供热量',
                            labelAlign: 'right',
                            name: 'geothermalAuxiliary'
                        },
                        {
                            xtype: 'numberfield',
                            id: 'solarPV',
                            padding: 2,
                            fieldLabel: '太阳能光电利用系统装机容量',
                            labelAlign: 'right',
                            name: 'solarPV'
                        },
                        {
                            xtype: 'hiddenfield',
                            id: 'id',
                            fieldLabel: 'Label',
                            name: 'id'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onBtnSaveClick: function(button, e, eOpts) {
        var me = this;
        var form = Ext.getCmp('ecform');
        if (form.isValid())
        {
            form.submit(
            {
                url : '../EnergyCollect!save.do',
                method : 'POST',
                waitMsg : '正在保存数据，稍后...',
                success : function(f, action)
                {
                    Ext.Msg.alert('信息提示', '保存成功');
                    me.close();
                },
                failure : function(f, action)
                {
                    if(action.response.status == 200)
                    {
                        var result = Ext.JSON.decode(action.response.responseText);
                        Ext.Msg.alert('信息提示', result.data);
                    }
                    else
                    {
                        Ext.Msg.alert('信息提示', action.response.responseText);
                    }
                }
            });
        }
    },

    onBtnResetClick: function(button, e, eOpts) {
        this.close();
    },

    bindFields: function(buildingId, buildingName, id) {
        var me = this;
        var formPanel = Ext.getCmp('ecform');
        Ext.getCmp('building.id').setValue(buildingId);
        Ext.getCmp('building.name').setValue(buildingName);
        var wait = Ext.Msg.wait("正在载入......", "操作提示");
        Ext.Ajax.request(
        {
            url : '../EnergyCollect.do',
            method : 'POST',
            params:{  
                id:id,
                buildingId:buildingId
            },  
            success : function(response, options)
            {
                wait.close();
                var result = Ext.JSON.decode(response.responseText); 
                if(result.success)
                {
                    var record = Ext.create('ems.model.EnergyConsumptionCollectModel');
                    record.data = result.data;
                    formPanel.loadRecord(record);  
                    Ext.getCmp('collectDate').setValue(new Date(record.data.collectDate.time));
                    Ext.getCmp('building.id').setValue(result.data.building.id);
                }
                else
                {
                    me.close();
                    Ext.Msg.alert('信息提示', result.data);
                }
            },
            failure : function(response, options)
            {
                wait.close();
                me.close();
                if(response.status == 200)
                {
                    var result = Ext.JSON.decode(response.responseText);
                    Ext.Msg.alert('信息提示', result.data);
                }
                else
                {
                    Ext.Msg.alert('信息提示', response.responseText);
                }
            }
        });
    }

});