/*
 * File: classes/store/BuildingStore.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ems.store.BuildingStore', {
    extend: 'Ext.data.Store',
    alias: 'store.BuildingStore',

    requires: [
        'ems.model.BuildingModel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            model: 'ems.model.BuildingModel',
            storeId: 'MyStore',
            proxy: {
                type: 'ajax',
                url: '../build!list.do'
            }
        }, cfg)]);
    }
});