/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    models: [
        'TreeModel'
    ],
    stores: [
        'PortalTreeStore',
        'OrganizationTreeStore'
    ],
    views: [
        'Portal',
        'PortalHeader',
        'PortalTree',
        'PortalFooter',
        'PortalTab',
        'PortalPanel',
        'OrganizationView',
        'OrganizationPanel'
    ],
    appFolder: 'classes',
    appProperty: 'gotom',
    autoCreateViewport: false,
    name: 'Gotom'
});

Ext.define('MyOrganizationPanel', {
    extend: 'OrganizationPanel',
    onOrganizationTreeItemClick: function(dataview, record, item, index, e, eOpts) {
        var ContentPanel = Ext.getCmp('ContentPanel');
        ContentPanel.setTitle('--'+record.data.text);
        ContentPanel.update('<iframe width="100%" height="100%" frameborder="0" src="http://www.baidu.com"></iframe>');
    }

});

Ext.onReady(function(){
    var view = Ext.create('Viewport');
    view.add(Ext.create('MyOrganizationPanel'));
});