/*
 * File: classes/view/LoginWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Login.view.LoginWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.LoginWindow',

    height: 250,
    id: 'LoginWindow',
    width: 400,
    layout: {
        type: 'border'
    },
    closable: false,
    title: '用户登录',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            listeners: {
                afterlayout: {
                    fn: me.onLoginWindowAfterLayout,
                    scope: me
                }
            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    layout: {
                        pack: 'center',
                        padding: 5,
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'button',
                            id: 'btnSubmit',
                            icon: './images/accept.png',
                            text: '登录',
                            listeners: {
                                click: {
                                    fn: me.onBtnSubmitClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'btnReset',
                            icon: './images/reset.png',
                            text: '重置',
                            listeners: {
                                click: {
                                    fn: me.onBtnResetClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'form',
                    region: 'center',
                    id: 'LoginForm',
                    layout: {
                        type: 'absolute'
                    },
                    bodyPadding: 10,
                    header: false,
                    title: '用户登录',
                    items: [
                        {
                            xtype: 'label',
                            x: 30,
                            y: 130,
                            baseCls: '',
                            cls: '',
                            componentCls: '',
                            disabledCls: '',
                            height: 40,
                            html: '  ',
                            id: 'formmsgLabel',
                            overCls: '',
                            padding: 5,
                            width: 340,
                            text: ''
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            x: 10,
                            y: 40,
                            id: 'loginusername',
                            fieldLabel: '用户名',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'loginusername'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            x: 10,
                            y: 80,
                            id: 'loginpassword',
                            fieldLabel: '密　码',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'loginpassword',
                            inputType: 'password'
                        },
                        {
                            xtype: 'label',
                            x: 30,
                            y: 10,
                            height: 30,
                            html: '<h3>请输入您的用户名和密码.</h3>',
                            width: 340,
                            text: ''
                        },
                        {
                            xtype: 'checkboxfield',
                            x: 80,
                            y: 110,
                            id: 'warnCheckbox',
                            boxLabel: '转向其他站点前提示我。'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onLoginWindowAfterLayout: function(container, layout, eOpts) {
        var username = document.getElementById('username').getAttribute('value');
        Ext.getCmp('loginusername').setValue(username);
        var password = document.getElementById('password').getAttribute('value');
        Ext.getCmp('loginpassword').setValue(password);
        //Ext.getCmp('warnCheckbox').setChecked(document.getElementById('warn').checked);
        var msg = '';
        if(document.getElementById('msg') != ''){
            msg = document.getElementById('msg').innerHTML;
        }
        Ext.getCmp('formmsgLabel').update('<div class="errors">'+msg+'</div>');
    },

    onBtnSubmitClick: function(button, e, eOpts) {
        var loginUsername = Ext.getCmp('loginusername');
        document.getElementById('username').setAttribute('value',loginUsername.getValue());
        var loginpassword = Ext.getCmp('loginpassword');
        document.getElementById('password').setAttribute('value',loginpassword.getValue());
        document.getElementById('warn').checked = Ext.getCmp('warnCheckbox').checked;
        document.getElementById("fm1").submit();
    },

    onBtnResetClick: function(button, e, eOpts) {
        Ext.getCmp('LoginForm').getForm().reset();
    }

});