/*
 * File: app/store/DemoTreeStore.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.DemoTreeStore', {
    extend: 'Ext.data.TreeStore',
    alias: 'store.DemoTreeStore',

    requires: [
        'MyApp.model.DemoModel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            model: 'MyApp.model.DemoModel',
            storeId: 'DemoTreeStore',
            defaultRootId: '',
            defaultRootText: '',
            nodeParam: 'id',
            proxy: {
                type: 'ajax',
                url: '../p/organization!tree.do',
                listeners: {
                    exception: {
                        fn: me.onAjaxException,
                        scope: me
                    }
                }
            }
        }, cfg)]);
    },

    onAjaxException: function(proxy, response, operation, eOpts) {
        alert(response.statusText);
    }

});