/*
 * File: app/view/BuildingFuncWin.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.BuildingFuncWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.BuildingFuncWin',

    height: 135,
    width: 370,
    layout: {
        type: 'border'
    },
    title: '建筑类别管理',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bindData: function(id) {
                        var formPanel = this;
                        var wait = Ext.Msg.wait("正在载入......","操作提示");
                        Ext.Ajax.request(
                        {
                            url:'../ems/buildfunc.do',
                            method:'POST',
                            params:{
                                id:id
                            },
                            success:function(response,options)
                            {
                                var result=Ext.JSON.decode(response.responseText);
                                var record=Ext.create('');
                                record.data=result;
                                wait.close();
                                formPanel.getForm().reset();
                                formPanel.loadRecord(record);
                            },
                            failure:function(response,options)
                            {
                                wait.close();
                                Ext.Msg.alert("操作提示","载入失败");
                            }
                        });
                    },
                    region: 'center',
                    id: 'BuildingFuncForm',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    items: [
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            id: '',
                            fieldLabel: '标识',
                            name: 'id'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            formBind: false,
                            fieldLabel: '编码',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'code',
                            invalidText: '编码不能为空！',
                            blankText: '编码不能为空！'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '名称',
                            labelAlign: 'right',
                            labelWidth: 60,
                            name: 'name',
                            invalidText: '名称不能为空！',
                            blankText: '名称不能为空！'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            id: 'bfEditToolBarl',
                            layout: {
                                pack: 'end',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'btnSave',
                                    iconCls: 'icon-save',
                                    text: '保存',
                                    listeners: {
                                        click: {
                                            fn: me.onBtnSaveClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    id: 'btnCancel',
                                    iconCls: 'icon-cancel',
                                    text: '取消',
                                    listeners: {
                                        click: {
                                            fn: me.onBtnCancelClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onBtnSaveClick: function(button, e, eOpts) {

    },

    onBtnCancelClick: function(button, e, eOpts) {
        this.close();
    },

    getForm: function() {
        return Ext.getCmp('BuildingFuncForm');
    }

});