/*
 * File: classes/view/Panel404.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('demo.view.Panel404', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.Panel404',

    layout: {
        type: 'border'
    },
    title: 'My Panel',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            listeners: {
                afterlayout: {
                    fn: me.onPanelAfterLayout,
                    single: true,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onPanelAfterLayout: function(container, layout, eOpts) {
        var me = this;
        Common.ajax({
            params:{id:''},
            component : me,
            message : '正在加载......',    
            url : ctxp+'/p/user!list.do',
            callback : function(result){}
        });
    }

});