/*
 * File: classes/model/YearReportDataModel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ems.model.YearReportDataModel', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'ConsumptionClass',
            type: 'string'
        },
        {
            name: 'JanValue',
            type: 'float'
        },
        {
            name: 'FebValue',
            type: 'float'
        },
        {
            name: 'MarValue',
            type: 'float'
        },
        {
            name: 'AprValue',
            type: 'float'
        },
        {
            name: 'MayValue',
            type: 'float'
        },
        {
            name: 'JuneValue',
            type: 'float'
        },
        {
            name: 'JulyValue',
            type: 'float'
        },
        {
            name: 'AugValue',
            type: 'float'
        },
        {
            name: 'SeptValue',
            type: 'float'
        },
        {
            name: 'OctValue',
            type: 'float'
        },
        {
            name: 'NovValue',
            type: 'float'
        },
        {
            name: 'DecValue',
            type: 'float'
        }
    ]
});