/*
 * File: classes/view/BuildingShartsTreePanel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ems.view.BuildingShartsTreePanel', {
    extend: 'Ext.tree.Panel',
    alias: 'widget.BuildingShartsTreePanel',

    id: 'BuildingShartsTreePanel',
    maxWidth: 400,
    minWidth: 100,
    width: 150,
    collapsed: false,
    collapsible: true,
    title: '建筑能耗报表',
    rootVisible: false,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {

            },
            selModel: Ext.create('Ext.selection.RowModel', {

            })
        });

        me.callParent(arguments);
    }

});