/*
 * File: classes/model/EnergyConsumptionCollectModel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ems.model.EnergyConsumptionCollectModel', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'geothermal'
        },
        {
            name: 'solarPV'
        },
        {
            name: 'geothermalAuxiliary'
        },
        {
            name: 'solarThermal'
        },
        {
            name: 'kerosene'
        },
        {
            name: 'gasoline'
        },
        {
            name: 'manufacturedGas'
        },
        {
            name: 'lpg'
        },
        {
            name: 'coal'
        },
        {
            name: 'otherEnergy'
        },
        {
            name: 'cooling'
        },
        {
            name: 'heating'
        },
        {
            name: 'gas'
        },
        {
            name: 'water'
        },
        {
            name: 'electric'
        },
        {
            name: 'id'
        },
        {
            name: 'collectDate'
        }
    ]
});