/*
 * File: classes/view/IndexPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Gotom.view.IndexPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.IndexPanel',

    requires: [
        'Gotom.view.PortalPanel',
        'Gotom.view.PortalColumn'
    ],

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            listeners: {
                afterlayout: {
                    fn: me.onPanelAfterLayout,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onPanelAfterLayout: function(container, layout, eOpts) {
        var portalPanel = Ext.create("Gotom.view.PortalPanel",
            {
                id : 'app-portal',
                region : 'center',
                title : "我的桌面",
                layout : 'column'
            });

        this.add(portalPanel);
    }

});