/*
 * File: classes/view/NoticeWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Gotom.view.NoticeWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.NoticeWindow',

    draggable: false,
    height: 250,
    padding: 2,
    width: 400,
    shadow: false,
    resizable: false,
    layout: {
        type: 'border'
    },
    animCollapse: true,
    closeAction: 'hide',
    collapseDirection: 'bottom',
    collapsible: true,
    title: '消息通知',
    titleAlign: 'center',
    titleCollapse: false,
    plain: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            listeners: {
                afterrender: {
                    fn: me.onWindowAfterRender,
                    single: true,
                    scope: me
                },
                collapse: {
                    fn: me.onWindowCollapse,
                    scope: me
                },
                expand: {
                    fn: me.onWindowExpand,
                    scope: me
                }
            },
            items: [
                {
                    xtype: 'panel',
                    region: 'center',
                    border: false,
                    bodyPadding: '5px',
                    header: false,
                    title: '消息内容',
                    listeners: {
                        render: {
                            fn: me.onPanelRender,
                            scope: me
                        }
                    }
                }
            ]
        });

        me.callParent(arguments);
    },

    onWindowAfterRender: function(component, eOpts) {
        this.resetPosition();
        Ext.EventManager.onWindowResize(this.resetPosition, this);
        this.loadNotice();
    },

    onWindowCollapse: function(p, eOpts) {
        this.resetPosition();
    },

    onWindowExpand: function(p, eOpts) {
        this.resetPosition();
    },

    onPanelRender: function(component, eOpts) {
        this.noticePanel = component;
    },

    resetPosition: function() {
        try{
            var width = this.width;
            var height = this.height;  
            if(this.collapsed === 'bottom' || this.collapsed === 'top')
            {
                height = 25;
            }
            if(this.collapsed === 'right' || this.collapsed === 'left')
            {
                width = 25;
            }    
            var body = Ext.getBody();
            var left = body.getWidth()-4-width;  
            var top = body.getHeight()-4-height;  
            this.setPosition(left, top);
        }catch(e){
            Ext.Msg.alert('title',e);
        }
    },

    loadNotice: function() {
        var me = this;
        me.resetPosition();
        var html = '<iframe width="100%" height="100%" frameborder="0" src="./resources/audiojs/audio.html"></iframe>';
        me.noticePanel.update(html);
        if(this.collapsed !== false)
        {
            me.expand();
        }
        if(me.hidden)
        {
            me.show();
        }
        //Ext.defer(function(){me.loadNotice();}, 1000);
    }

});