/*
 * File: classes/view/OrganizationCRUB.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Gotom.view.OrganizationCRUB', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Gotom.view.OrganizationTreeGrid',
        'Gotom.model.OrganizationModel',
        'Gotom.store.OrganizationTreeStore'
    ],

    id: 'OrganizationCRUB',
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'OrganizationTreeGrid',
                    region: 'center'
                }
            ]
        });

        me.callParent(arguments);
    }

});