/*
 * File: classes/view/RightPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Gotom.view.RightPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.RightPanel',

    requires: [
        'Gotom.model.RightTreeCheckModel'
    ],

    border: false,
    autoScroll: true,
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'treepanel',
                    region: 'center',
                    split: true,
                    stateful: true,
                    id: 'RightTreePanel',
                    autoScroll: true,
                    animate: true,
                    rootVisible: false,
                    viewConfig: {
                        stateful: true,
                        id: 'RightTreePanelView',
                        listeners: {
                            itemclick: {
                                fn: me.onRightTreePanelViewItemClick,
                                scope: me
                            }
                        }
                    },
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            id: 'RightTreePanelToolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    iconCls: 'icon-refresh',
                                    text: '刷新',
                                    listeners: {
                                        click: {
                                            fn: me.onRefClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    iconCls: 'icon-add',
                                    text: '添加目录',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonAddClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    iconCls: 'icon-add-p',
                                    text: '添加资源',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonNewClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    iconCls: 'icon-edit',
                                    text: '修改',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonEditClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    iconCls: 'icon-del',
                                    text: '删除',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonDelClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    iconCls: 'icon-file',
                                    text: '导出',
                                    listeners: {
                                        click: {
                                            fn: me.onDownDelClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'form',
                                    border: false,
                                    width: 180,
                                    layout: {
                                        type: 'fit'
                                    },
                                    header: false,
                                    title: '导入',
                                    items: [
                                        {
                                            xtype: 'filefield',
                                            width: 176,
                                            fieldLabel: '文件',
                                            hideLabel: true,
                                            labelAlign: 'right',
                                            name: 'upload',
                                            buttonText: '导入',
                                            listeners: {
                                                change: {
                                                    fn: me.onFilefieldChange,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ],
                                    listeners: {
                                        beforerender: {
                                            fn: me.onFormBeforeRender,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ],
                    columns: [
                        {
                            xtype: 'treecolumn',
                            width: 200,
                            sortable: false,
                            dataIndex: 'text',
                            menuDisabled: true,
                            text: '菜单名称',
                            flex: 1
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'iconCls',
                            text: '使用样式'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 200,
                            defaultWidth: 160,
                            dataIndex: 'component',
                            text: '控件或连接'
                        },
                        {
                            xtype: 'gridcolumn',
                            defaultWidth: 200,
                            sortable: false,
                            dataIndex: 'resource',
                            text: '数据资源',
                            flex: 1
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'sort',
                            text: '排列顺序'
                        }
                    ],
                    listeners: {
                        afterrender: {
                            fn: me.onRightTreePanelAfterRender,
                            single: true,
                            scope: me
                        }
                    },
                    selModel: Ext.create('Ext.selection.RowModel', {

                    })
                }
            ]
        });

        me.callParent(arguments);
    },

    onRightTreePanelViewItemClick: function(dataview, record, item, index, e, eOpts) {
        var me = this;
        if(record.data.checked)
        {
            record.set('checked', false);
            Common.onTreePanelCheckChange(record,false);
        }
        else
        {
            record.set('checked', true);
        }
        Common.onTreeChildNodesChecked(record,record.data.checked);
    },

    onRefClick: function(button, e, eOpts) {
        this.loadRight();
    },

    onButtonAddClick: function(button, e, eOpts) {
        this.onBtnAddClick(false);
    },

    onButtonNewClick: function(button, e, eOpts) {
        this.onBtnAddClick(true);
    },

    onButtonEditClick: function(button, e, eOpts) {
        var me = this;
        var selected = me.treePanel.getSelectionModel().selected;
        var record = selected.items[0];
        if(!Ext.isEmpty(record))
        {
            Common.ajax({
                params:{id:record.data.id},
                component : me,
                message : '正在加载......',    
                url : ctxp+'/p/right.do',
                callback : function(result)
                {
                    var recordData = Ext.create('Gotom.model.RightTreeCheckModel');
                    recordData.data = result;        
                    me.showform(recordData);
                }
            });    
        }
    },

    onButtonDelClick: function(button, e, eOpts) {
        var ids = [];
        var tree = this.treePanel;
        var items = tree.getSelectionModel().store.data.items;
        Ext.each(items, function()
        {
            var nd = this;
            if(nd.data.checked)
            {
                ids.push(nd.data.id);
            }
        });
        if (ids.length === 0)
        {
            Ext.Msg.show(
            {
                // width : 200
                title : "操作提示",
                msg : "请选择要删除的节点!",
                icon : Ext.Msg.WARNING
            });
            return;
        }
        Ext.Msg.confirm("警告", "确定要删除吗？", function(button)
        {
            if (button == "yes")
            {
                Ext.Msg.wait("正在执行......", "操作提示");
                Ext.Ajax.request(
                {
                    url : ctxp + '/p/right!remove.do',
                    method : 'POST',
                    params :
                    {
                        id : ids
                    },
                    success : function(response, options)
                    {
                        Ext.Msg.alert("删除提示", "删除成功");
                        tree.getStore().reload();
                        Ext.defer(function(){tree.expandAll();},100);
                    },
                    failure : function(response, options)
                    {
                        Ext.Msg.alert("删除提示", "删除失败");
                    }
                });
            }
        });
    },

    onDownDelClick: function(button, e, eOpts) {
        window.open(ctxp + '/p/right!down.do');
    },

    onFilefieldChange: function(filefield, value, eOpts) {
        var me = this;
        try{
            Common.submit({  
                url : ctxp+'/p/right!up.do',
                form:me.upForm,
                callback : function(result)
                {
                    Ext.Msg.alert('信息提示', result.data);	
                }
            });
        }catch(error){
            Ext.Msg.alert('信息提示', error);
        }
    },

    onFormBeforeRender: function(component, eOpts) {
        this.upForm = component;
    },

    onRightTreePanelAfterRender: function(component, eOpts) {
        this.treePanel = component;
        this.loadRight();
    },

    onBtnAddClick: function(leaf) {
        var me = this;
        var selected = me.treePanel.getSelectionModel().selected;
        var p = selected.items[0];
        var parentId = '';
        if (!Ext.isEmpty(p, false))
        {
            parentId = p.data.id;
            if (p.data.leaf)
            {
                Ext.Msg.alert("操作提示", "请选择目录类型节点！");
                return;
            }
        }
        Common.ajax({
            params:{id:''},
            component : me,
            message : '正在加载......',    
            url : ctxp+'/p/right.do',
            callback : function(result)
            {
                var record = Ext.create('Gotom.model.RightTreeCheckModel');
                result.parentId = parentId;
                record.data = result;
                record.data.leaf = leaf;
                if(leaf){
                    record.data.type = 'URL';
                }else{
                    record.data.type = 'DIR';
                }       
                me.showform(record);
            }
        });
    },

    showform: function(record) {
        var me = this;
        if (record !== null && record !== '')
        {
            var formwin = Ext.create('Gotom.view.RightWindow');
            formwin.addListener('close', function(panel,opts)
            {
                me.loadRight();
            });
            formwin.show();
            formwin.form.getForm().reset();
            formwin.form.loadRecord(record);
        }
        else
        {
            Ext.Msg.show(
            {
                // width : 200
                title : "操作提示",
                msg : "请选择要修改的节点!",
                icon : Ext.Msg.WARNING
            });
        }
    },

    loadRight: function() {
        var me = this;
        var myStore = Ext.create("Ext.data.TreeStore",
            {
                defaultRootId : '',
                clearOnLoad : true,
                nodeParam : 'id',
                model : 'Gotom.model.RightTreeCheckModel',
                proxy :
                {
                    type : "ajax",
                    url : ctxp+'/p/right!tree.do',
                    listeners: {
                        exception: function(proxy, response, operation, eOpts)
                        {
                            Common.onAjaxException(response,me);
                    }
                }            
            }    
        });
        me.treePanel.bindStore(myStore);
        myStore.reload();
        me.treePanel.expandAll();
        Ext.defer(function()
        {
            me.treePanel.expandAll();
        }, 1000);
    }

});