/*
 * File: classes/view/RolePanel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Gotom.view.RolePanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.RolePanel',

    id: 'RolePanel',
    layout: {
        type: 'border'
    },
    header: false,
    title: '角色管理',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            iconCls: 'icon-add',
                            text: '新增',
                            listeners: {
                                click: {
                                    fn: me.onBtnNewClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            iconCls: 'icon-edit',
                            text: '修改',
                            listeners: {
                                click: {
                                    fn: me.onBtnEditClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            iconCls: 'icon-del',
                            text: '删除',
                            listeners: {
                                click: {
                                    fn: me.onBtnDelClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            iconCls: 'icon-save',
                            text: '保存',
                            listeners: {
                                click: {
                                    fn: me.onBtnSaveClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            iconCls: 'icon-refresh',
                            text: '刷新',
                            listeners: {
                                click: {
                                    fn: me.onBtnRefClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    region: 'west',
                    id: 'RoleGridPanel',
                    width: 250,
                    title: '角色列表',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            id: 'RoleGridName',
                            width: 130,
                            dataIndex: 'name',
                            text: '权限名称'
                        },
                        {
                            xtype: 'numbercolumn',
                            id: 'RoleGridSort',
                            width: 94,
                            dataIndex: 'sort',
                            text: '排列顺序',
                            format: '0,000'
                        }
                    ],
                    viewConfig: {
                        listeners: {
                            itemclick: {
                                fn: me.onViewItemClick,
                                scope: me
                            }
                        }
                    },
                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                    }),
                    tools: [
                        {
                            xtype: 'tool',
                            type: 'refresh',
                            listeners: {
                                click: {
                                    fn: me.onToolClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    id: 'CenterPanel',
                    layout: {
                        type: 'border'
                    },
                    items: [
                        {
                            xtype: 'form',
                            region: 'north',
                            border: false,
                            height: 123,
                            id: 'RoleForm',
                            bodyPadding: 10,
                            title: '编辑角色',
                            items: [
                                {
                                    xtype: 'hiddenfield',
                                    anchor: '100%',
                                    fieldLabel: 'Label',
                                    name: 'role.id'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    anchor: '100%',
                                    fieldLabel: 'Label',
                                    name: 'rightIds'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: '权限名称',
                                    name: 'role.name',
                                    allowBlank: false,
                                    enforceMaxLength: false,
                                    maxLength: 50,
                                    minLength: 2
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    fieldLabel: '排列顺序',
                                    name: 'role.sort'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    anchor: '100%',
                                    fieldLabel: 'Label',
                                    name: 'role.organizationId'
                                },
                                {
                                    xtype: 'panel',
                                    border: false,
                                    height: 29,
                                    layout: {
                                        type: 'anchor'
                                    },
                                    header: false,
                                    title: '所属部门',
                                    titleCollapse: false,
                                    listeners: {
                                        afterlayout: {
                                            fn: me.onPanelAfterLayout,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ],
            listeners: {
                afterlayout: {
                    fn: me.onRolePanelAfterLayout,
                    single: true,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onBtnNewClick: function(button, e, eOpts) {
        this.loadFormData('');
    },

    onBtnEditClick: function(button, e, eOpts) {
        var selected = Ext.getCmp('RoleGridPanel').getSelectionModel().selected;
        var record = selected.items[0];
        if(!Ext.isEmpty(record))
        {
            this.loadFormData(record.data.id);
        }
        else
        {
            Ext.Msg.alert('操作提示','请选择要修改的列!');
        }
    },

    onBtnDelClick: function(button, e, eOpts) {
        this.deleteRole();
    },

    onBtnSaveClick: function(button, e, eOpts) {
        this.saveForm();
    },

    onBtnRefClick: function(button, e, eOpts) {
        this.loadRoleGrid();
        this.loadFormData('');
    },

    onViewItemClick: function(dataview, record, item, index, e, eOpts) {
        this.loadFormData(record.data.id);
    },

    onToolClick: function(tool, e, eOpts) {
        this.loadRoleGrid();
    },

    onPanelAfterLayout: function(container, layout, eOpts) {
        this.orgTreePanel = container;
    },

    onRolePanelAfterLayout: function(container, layout, eOpts) {
        this.loadRoleGrid();
        this.loadFormData('');
    },

    loadRoleGrid: function() {
        var me = this;
        Common.ajax({
            component : me,
            message : '正在加载......',    
            url : ctxp+'/p/role!list.do',
            callback : me.bindRoleGrid
        });
    },

    bindRoleGrid: function(result) {
        var me = this;
        var roleStore = Ext.create('Ext.data.Store', {
            storeId:'roleStore',
            fields: [
            {
                name: 'id'
            },
            {
                name: 'name'
            },
            {
                name: 'sort'
            }
            ],
            data : result.data,
            proxy:
            {
                type: 'memory',
                reader:{
                    type: 'json'
                }
            }
        });
        Ext.getCmp('RoleGridPanel').bindStore(roleStore); 
    },

    loadFormData: function(roleId) {
        var me = this;
        var form = Ext.getCmp('RoleForm');
        me.orgTreePanel.removeAll();
        var treeComboBox = Ext.create('Gotom.view.RoleOrgTreeComboBox', {
            url : ctxp+'/p/role!orgTree.do?role.id='+roleId,
            anchor: '100%',
            fieldLabel: '所在部门',
            labelWidth: 100,
            name: 'orgname'    
        });
        me.orgTreePanel.items.add(treeComboBox);
        try{

            Common.ajax({
                component : me,
                params:{'role.id':roleId},  
                message : '加载信息...',    
                url : ctxp+'/p/role.do',
                callback : function(result)
                {
                    if(result.success)
                    {
                        me.bindRightTree(result.role.id);
                        form.getForm().findField('role.id').setValue(result.role.id);
                        form.getForm().findField('role.name').setValue(result.role.name);                
                        form.getForm().findField('role.sort').setValue(result.role.sort); 
                        form.getForm().findField('role.organizationId').setValue(result.role.organization.id);
                        treeComboBox.setValue(result.role.organization.text);  
                        treeComboBox.selected = result.role.organization.id;
                    }
                    else
                    {
                        Ext.Msg.alert('信息提示', result.data);
                    }    	
                }
            });
        }catch(error){
            alert(error);
        }
    },

    bindRightTree: function(roleId) {
        var me = this;
        var myStore = Ext.create("Ext.data.TreeStore",
            {
                defaultRootId : roleId,
                clearOnLoad : true,
                nodeParam : 'role.id',
                fields: [
                {
                    name: 'id'
                },
                {
                    name: 'parentId'
                },
                {
                    name: 'text'
                },
                {
                    name: 'component'
                },
                {
                    name: 'resource'
                },
                {
                    name: 'iconCls'
                },
                {
                    name: 'checked',
                    type: 'boolean'
                }
                ],
                proxy :
                {
                    type : 'ajax',
                    url : ctxp+'/p/role!tree.do'             
                }                      
            });
        var tree = Ext.create('Ext.tree.Panel',
            {
                region: 'center',
                id: 'RoleRightTreePanel',
                title: '角色可访问资源',
                animate : true,
                border : false,
                bodyborder : false,
                lines : true,
                split : true,
                stateful : true,
                collapsible : false,
                frame : false,
                enableDD : true,
                autoScroll : true,
                autoHeight : false,
                rootVisible : false,
                multiSelect : false,
                store:myStore,
                root :
                {
                    expanded : true
                },
                listeners: {
                    itemclick: 
                    {
                        fn: me.onTreeItemClick,
                        scope: me
                    },
                    checkchange: 
                    {
                        fn: Common.onTreePanelCheckChange,
                        scope: me
                    }
                },        
                columns : [
                {
                    xtype : 'treecolumn',
                    dataIndex : 'text',
                    text : '菜单名称',
                    sortable : false,
                    flex : 1,
                    width:300,
                    menuDisabled : true
                },
                {
                    xtype : 'gridcolumn',
                    dataIndex : 'iconCls',
                    text : '使用样式'
                },
                {
                    xtype : 'gridcolumn',
                    dataIndex : 'component',
                    width:200,
                    text : '控件或连接'
                },
                {
                    xtype : 'gridcolumn',
                    dataIndex : 'resource',
                    width:200,
                    text : '数据资源'
                }]
            });
        tree.expandAll();
        Ext.getCmp('CenterPanel').remove(1);
        Ext.getCmp('CenterPanel').add(tree);

    },

    saveForm: function() {
        var me = this;
        var form = Ext.getCmp('RoleForm');
        try{
            var selected = me.orgTreePanel.items.get(0).selected;
            if(selected.length === 0){
                Ext.Msg.alert('信息提示', '请选择所在部门！');
                return;        
            }
            form.getForm().findField('role.organizationId').setValue(selected);
            var rightIds = [];
            var tree = Ext.getCmp('RoleRightTreePanel');
            var items = tree.getSelectionModel().store.data.items;
            Ext.each(items, function()
            {
                var nd = this;
                if(nd.data.checked)
                {
                    rightIds.push(nd.data.id);
                }
            });    
            form.getForm().findField('rightIds').setValue(rightIds);
            Common.formSubmit({  
                url : ctxp+'/p/role!save.do',
                form:form,
                callback : function(result)
                {
                    if(result.success)
                    {
                        me.loadRoleGrid();
                        me.loadFormData('');
                    }else{
                        Ext.Msg.alert('信息提示', result.data);
                    }	
                }
            });
        }catch(error){
            alert(error);
        }

    },

    deleteRole: function() {
        var me = this;
        var selected = Ext.getCmp('RoleGridPanel').getSelectionModel().selected;
        var selecteditems = selected.items;
        if (selecteditems.length === 0)
        {
            Ext.Msg.show(
            {
                title : "操作提示",
                msg : "请选择要删除的节点!",
                icon : Ext.Msg.WARNING
            });
            return;
        }
        var ids = [];
        Ext.each(selecteditems, function()
        {
            var nd = this;
            ids.push(nd.data.id);
        });
        Ext.Msg.confirm("警告", "确定要删除吗？", function(button)
        {
            if (button == "yes")
            {
                Ext.Msg.wait("正在执行......", "操作提示");
                Ext.Ajax.request(
                {
                    url : ctxp+'/p/role!remove.do',
                    method : 'POST',
                    params :
                    {
                        'role.id' : ids.join(",")
                    },
                    success : function(response, options)
                    {
                        Ext.Msg.alert("删除提示", "删除成功");
                        me.loadRoleGrid();
                        me.loadFormData('');
                    },
                    failure : function(response, options)
                    {
                        Ext.Msg.alert("删除提示", "删除失败<br/>"+response.responseText);
                    }
                });
            }
        });
    },

    onTreeItemClick: function(dataview, record, item, index, e, eOpts) {
        if(record.data.checked)
        {
            record.set('checked', false);
            Common.onTreePanelCheckChange(record,false,eOpts);
        }
        else
        {
            record.set('checked', true);
            Common.onTreePanelCheckChange(record,true,eOpts);
        }
    }

});