/*
 * File: classes/view/Commons.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Gotom.view.Commons', {
    extend: 'Ext.Base',
    alias: 'widget.Commons',

    ctxp: '',

    ajax: function(config) {
        Ext.Ajax.request(
        {
            url : config.url,
            params : config.params,
            method : 'post',

            callback : function(options, success, response)
            {
                if (success)
                {
                    config.callback(Ext.JSON.decode(response.responseText),options, success, response);// 调用回调函数
                }
                else
                {
                    Ext.Msg.alert('信息提示', response.responseText);
                }
            }
        });
    },

    treeStore: function(url, pid, treeModel) {
        return Ext.create("Ext.data.TreeStore",
        {
            defaultRootId : pid,
            model : treeModel,
            proxy :
            {
                type : "ajax",
                url : url
            },
            clearOnLoad : true,
            nodeParam : "id"
        });
    },

    getQueryParam: function(name) {
        var regex = RegExp('[?&]' + name + '=([^&]*)');
        var scriptEls = document.getElementsByTagName('script');
        var path = scriptEls[scriptEls.length - 1].src;
        var match = regex.exec(location.search) || regex.exec(path);
        return match && decodeURIComponent(match[1]);
    },

    addQueryParam: function(url, name, value) {
        var path = url;
        if (value !== null && value.length > 0)
        {
            if (url.indexOf('?') >= 0)
            {
                path = url + '&' + name + '=' + value;
            }
            else
            {
                path = url + '?' + name + '=' + value;
            }
        }
        return path;
    }

});