/*
 * File: classes/view/OrganizationPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Gotom.view.OrganizationPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.OrganizationPanel',

    id: 'OrganizationPanel',
    layout: {
        type: 'border'
    },
    header: false,
    title: 'PortalPanel',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'treepanel',
                    region: 'west',
                    split: true,
                    id: 'OrganizationTree',
                    maxWidth: 400,
                    minWidth: 120,
                    width: 150,
                    autoScroll: true,
                    bodyBorder: false,
                    animCollapse: true,
                    collapsed: false,
                    collapsible: true,
                    overlapHeader: false,
                    title: '组织架构',
                    titleCollapse: false,
                    columnLines: false,
                    store: 'OrganizationTreeStore',
                    rootVisible: false,
                    listeners: {
                        itemclick: {
                            fn: me.onOrganizationTreeItemClick,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    id: 'ContentPanel',
                    title: 'ContentPanel'
                }
            ]
        });

        me.callParent(arguments);
    },

    onOrganizationTreeItemClick: function(dataview, record, item, index, e, eOpts) {
        var ContentPanel = Ext.getCmp('ContentPanel');
        ContentPanel.setTitle(record.data.text);
        ContentPanel.update('<iframe width="100%" height="100%" frameborder="0" src="http://www.google.com.hk"></iframe>');
    }

});