/*
 * File: classes/view/OrganizationWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Gotom.view.OrganizationWindow', {
    extend: 'Ext.window.Window',

    requires: [
        'Gotom.view.OrganizationForm'
    ],

    height: 179,
    id: 'OrganiztionWindow',
    width: 400,
    layout: {
        type: 'border'
    },
    title: '组织架构',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'OrganizationForm',
                    region: 'center',
                    bodyPadding: 20
                }
            ]
        });

        me.callParent(arguments);
    },

    getForm: function() {
        return Ext.getCmp('OrganizationForm');
    }

});