/*
 * File: classes/view/UserPassowrd.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Gotom.view.UserPassowrd', {
    extend: 'Ext.window.Window',

    height: 164,
    width: 400,
    layout: {
        type: 'border'
    },
    closeAction: 'hide',
    title: '修改密码',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    region: 'center',
                    id: 'passwordForm',
                    bodyPadding: 10,
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            layout: {
                                pack: 'end',
                                padding: 3,
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    iconCls: 'icon-save',
                                    text: '保存',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            id: 'userid',
                            fieldLabel: 'Label',
                            name: 'user.id'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            id: 'username',
                            fieldLabel: 'Label',
                            name: 'user.username'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            id: 'user.password',
                            fieldLabel: '原 密 码',
                            name: 'user.password'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            id: 'user.newpass',
                            fieldLabel: '新 密 码',
                            name: 'user.newpass'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            id: 'user.newpassCheck',
                            fieldLabel: '确认密码',
                            name: 'user.newpassCheck'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {

    }

});