/*
 * File: app/view/BuildingGrid.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.BuildingGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.BuildingGrid',

    height: 375,
    width: 556,
    title: '建筑信息管理',
    store: 'BuildingStore',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'code',
                    text: '编码'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'name',
                    text: '名称'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    id: 'bToolBar',
                    items: [
                        {
                            xtype: 'button',
                            id: 'btnBRef',
                            iconCls: 'icon-refresh',
                            text: '刷新',
                            listeners: {
                                click: {
                                    fn: me.onBtnBRefClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'btnBNew',
                            iconCls: 'icon-add',
                            text: '新增'
                        },
                        {
                            xtype: 'button',
                            id: 'btnBEdit',
                            iconCls: 'icon-edit',
                            text: '修改'
                        },
                        {
                            xtype: 'button',
                            id: 'btnBDel',
                            iconCls: 'icon-del',
                            text: '删除'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onBtnBRefClick: function(button, e, eOpts) {
        window.location.reload();
    }

});